[package]
name = "f4yking/logmodule"
description = "Discord Webhook logger."
version = "1.0.0"
license = "MIT"
authors = ["F4YKING"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"