[package]
name = "f4yking/logmodule"
description = "Discord Webhook logger."
version = "0.1.1"
license = "MIT"
authors = ["F4YKING"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"