[package]
name = "f4yking/logmodule"
description = "Discord Webhook logger."
version = "1.0.11"

license = "MIT"
authors = ["F4YKING"]

realm = "server"
registry = "https://github.com/UpliftGames/wally-index"

exclude = ["**"]
include = ["LogModule", "LogModule/*", "default.project.json", "wally.toml"]

private = false